// Generated by CoffeeScript 1.9.2
var app, data, express, makeIdArray, nomo, url;

express = require('express');

url = require('url');

nomo = require('node-monkey').start();

app = express();

data = require('./dummy-data');

app.use(express["static"](__dirname + '/public'));

app.use(express.bodyParser());

app.get('/api/:type', function(req, res) {
  var collection, ids, j, len, model, out, type;
  type = req.params.type;
  collection = data[type];
  console.log('foobar');
  ids = req.query.ids;
  if (!ids) {
    out = collection;
  } else {
    ids = makeIdArray(ids);
    console.log(ids);
    out = [];
    for (j = 0, len = collection.length; j < len; j++) {
      model = collection[j];
      if (ids.indexOf(model.id) >= 0) {
        out.push(model);
      }
    }
  }
  if (out.length === 1) {
    out = out[0];
  }
  res.writeHead(200, {
    'Content-type': 'application/json'
  });
  return res.end(JSON.stringify(out));
});

app.post('/api/:type', function(req, res) {
  var atts, biggestId, item, j, len, ref, type;
  type = req.params.type;
  biggestId = 0;
  ref = data[type];
  for (j = 0, len = ref.length; j < len; j++) {
    item = ref[j];
    if (item.id > 0) {
      biggestId = item.id;
    }
  }
  atts = req.body;
  atts.id = biggestId + 1;
  data[type].push(atts);
  res.writeHead(200, {
    'Content-type': 'application/json'
  });
  return res.end(JSON.stringify(atts));
});

makeIdArray = function(ids) {
  var i, id, j, len, results;
  ids = ids.split(',');
  results = [];
  for (i = j = 0, len = ids.length; j < len; i = ++j) {
    id = ids[i];
    results.push(ids[i] = parseInt(id));
  }
  return results;
};

app.listen(3000);
